tabWidth: 4
printWidth: 120
singleQuote: true
bracketSpacing: true
jsxBracketSameLine: true
semi: true
trailingComma: 'all'
jsxSingleQuote: false
quoteProps: 'as-needed'
arrowParens: 'always'
endOfLine: 'lf'
